Rails.application.routes.draw do
  root 'page#home'

  get 'foods_read/home' #beans
  get 'foods_read/beef_page_one'
  get 'foods_read/bread_page_two'
  get 'foods_read/cafeteria_page_three'
  get 'foods_read/chicken_page_four'
  get 'foods_read/fish_page_five'
  get 'foods_read/pasta_page_six'
  get 'foods_read/pork_page_seven'
  get 'foods_read/potato_page_eight'
  get 'foods_read/rice_page_nine'
  get 'foods_read/salad_page_ten'

  get 'foods_match/home' #want_chicken
  get 'foods_match/want_potatoes'
  get 'foods_match/want_beans'
  get 'foods_match/want_rice'
  get 'foods_match/want_fish'
  get 'foods_match/want_beef'
  get 'foods_match/want_bread'
  get 'foods_match/want_pasta'
  get 'foods_match/want_pork'
  get 'foods_match/want_salad'
  get 'foods_match/yes_want_chicken'
  get 'foods_match/yes_want_potatoes'
  get 'foods_match/yes_want_beans'
  get 'foods_match/yes_want_rice'
  get 'foods_match/yes_want_bread'
  get 'foods_match/yes_want_pasta'
  get 'foods_match/yes_want_salad'
  get 'foods_match/no_fish'
  get 'foods_match/no_beef'
  get 'foods_match/no_pork'


  get 'places_read/home' #bank
  get 'places_read/bus_stop_page_one'
  get 'places_read/church_page_two'
  get 'places_read/class_page_three'
  get 'places_read/downtown_page_four'
  get 'places_read/home_page_five'
  get 'places_read/mosque_page_six'
  get 'places_read/park_page_seven'
  get 'places_read/store_page_eight'
  get 'places_read/work_page_nine'

  get 'places_match/home' #where are you going?
  get 'places_match/store_going'
  get 'places_match/bank_going'
  get 'places_match/park_going'
  get 'places_match/home_going'
  get 'places_match/mosque_going'
  get 'places_match/church_going'
  get 'places_match/work_going'
  get 'places_match/school_going'
  get 'places_match/busstop_going'
  get 'places_match/downtown_going'
  get 'places_match/store_question_going'
  get 'places_match/bank_question_going'
  get 'places_match/park_question_going'
  get 'places_match/home_question_going'
  get 'places_match/mosque_question_going'
  get 'places_match/church_question_going'
  get 'places_match/work_question_going'
  get 'places_match/school_question_going'
  get 'places_match/busstop_question_going'
  get 'places_match/downtown_question_going'

  get 'actions_read/home' #watchtv
  get 'actions_read/cook_page_one'
  get 'actions_read/dolaundry_page_two'
  get 'actions_read/playsoccer_page_three'
  get 'actions_read/sleep_page_four'
  get 'actions_read/visit_page_five'
  get 'actions_read/walk_page_six'

  get 'actions_match/home' #she is cooking
  get 'actions_match/she_is_cooking'
  get 'actions_match/she_is_cleaning'
  get 'actions_match/doing_laundry'
  get 'actions_match/visiting_sister'
  get 'actions_match/are_walking'
  get 'actions_match/are_playing_soccer'
  get 'actions_match/watching_tv'
  get 'actions_match/is_sleeping'
  get 'actions_match/what_she_doing'
  get 'actions_match/what_they_doing'
  get 'actions_match/what_he_doing'
  get 'actions_match/what_did_yesterday'
  get 'actions_match/i_cleaned'
  get 'actions_match/i_cooked'
  get 'actions_match/did_laundry'
  get 'actions_match/visited_sister'
  get 'actions_match/i_walked'
  get 'actions_match/played_soccer'
  get 'actions_match/watched_tv'
  get 'actions_match/i_slept'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
